spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8016

logging:
  file:
    name: logs/reactjavaproj1.log
    path: reactjavaproj1
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























